# Generated by Django 4.0.5 on 2022-08-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='config_mail',
            field=models.TextField(blank=True, choices=[('Select one configuration to use e-mail customize app', 'Select one configuration to use e-mail customize app'), ('Configure Send by my e-mail', 'Configure Send by my e-mail'), ('Forward to my email', 'Forward to my email')], max_length=100, null=True),
        ),
    ]
