# Generated by Django 4.0.5 on 2022-07-23 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',)},
        ),
        migrations.AddField(
            model_name='room',
            name='authorized_users',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_picture',
            field=models.FileField(default='room_pictures/default.jpeg', upload_to='room_pictures'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.TextField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Group', 'Group')], default=datetime.date(2022, 7, 23), max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AccountChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(blank=True, max_length=100000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
