# Generated by Django 4.0.6 on 2022-09-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=40)),
                ('player1', models.CharField(max_length=40)),
                ('player2', models.CharField(max_length=40)),
                ('num_players', models.CharField(max_length=40)),
            ],
        ),
    ]
