# Generated by Django 4.0.6 on 2022-09-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_alter_match_num_players_alter_match_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
